### ISSUE TITLE
Dispatch work to a thread pool

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#102]
https://docs.rs/threadpool

**Comment by karan1276** [comment]
Demo i wrote for that can be found here: https://github.com/karan1276/rust-demo

**Comment by dtolnay** [comment]
Nice! Are you still working on turning this into a PR or would you need someone else to take over?

**Comment by leodasvacas** [comment]
I think the example should use the [Rayon thread pool](https://docs.rs/rayon/0.7.0/rayon/struct.ThreadPool.html), it's a more popular implementation.

**Comment by llambda** [comment]
May want to consider https://github.com/carllerche/futures-threadpool since it returns futures.

**Comment by budziq** [comment]
I'd like to try this one. 

It would be drawing a fractal (julia set) to an image with threadpool.
