### ISSUE TITLE
Access a file randomly using a memory map

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#105]
https://docs.rs/memmap/*/memmap/struct.Mmap.html

**Comment by DeltaManiac** [comment]
@dtolnay 
If you could provide a bit more description on what would the example would be it would be super awesome.

I was thinking of loading  an audio file and printing out the data on to stdio.

Do let me know if you have something in mind and I'd like to work on it even though I am a newb. 😆

**Comment by dtolnay** [comment]
I think the key piece here is going to be accessing the file in an order that is not straight beginning-to-end. Mmap is convenient for this because you aren't required to write explicit [seek](https://doc.rust-lang.org/std/fs/struct.File.html#method.seek) calls to jump around the file. Can you think of any use cases like that?

**Comment by dtolnay** [comment]
Added in #177.
