### ISSUE TITLE
Use HEAD request to test whether endpoint exists

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#109]
For example, check whether a particular GitHub user exists: https://api.github.com/users/ferris-the-crab

**Comment by gsquire** [comment]
I can do this one using the `reqwest` crate.

**Comment by dtolnay** [comment]
Great! [Here is a method to make a HEAD request](https://docs.rs/reqwest/0.6.1/reqwest/struct.Client.html#method.head) and GitHub should respond with 200 if the user exists and 404 if the user does not exist (or come up with your own better use case).
