### ISSUE TITLE
"Define and operate on a type represented as a bitfield" recipe 

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#114]
The [`bitflags`](https://docs.rs/bitflags/*/bitflags/macro.bitflags.html) crate was reviewed by the libs team before the Libz Blitz was announced, but there are no cookbook examples for it yet. Come up with a compelling use case, possibly inspired by real usage on crates.io! [reverse dependencies](https://crates.io/crates/bitflags/reverse_dependencies)

cc https://github.com/brson/rust-cookbook/issues/190

**Comment by budziq** [comment]
Hmm, maybe a synthetic example:
- like gamepad state example in https://en.wikipedia.org/wiki/Bit_field#Unix_process_exit_code

or some low level stuff:
- checking flags in [gzipped archive](http://www.zlib.org/rfc-gzip.html#file-format) or some image or multimedia file format in order not to collide with other specialized crates. But not wanting to roll a whole parser or pull one of the parser combinator crates. 
- interacting with some c ffi like in https://github.com/nix-rust/nix/search?utf8=%E2%9C%93&q=bitflags&type=

**Comment by brson** [comment]
I'm not sure if bitflags makes any particular guarantees about its representation that would allow it to interop with C.

**Comment by budziq** [comment]
I meant something along the lines of https://github.com/nix-rust/nix/blob/c086d23997ca1c887377bc78fd3fa79000a810d7/src/fcntl.rs#L215

From the very first paragraph of bitflags crate doc:
> A typesafe bitmask flag generator useful for sets of C-style bitmask flags. It can be used for creating typesafe wrappers around C APIs.

**Comment by tyoc213** [comment]
I will try this... but I also dont know how this is related to #189

**Comment by budziq** [comment]
hi @tyoc213.
this example is already implemented https://github.com/brson/rust-cookbook/pull/192   and waits for merge (due to bug in skeptic).

If you have a fundamentally different example in mind feel free to make a PR. Otherwise would you consider solving one of the other issues or proposing other examples?

**Comment by budziq** [comment]
> but I also dont know how this is related to #189

unfortunately it is a duplicate. I will close it

**Comment by tyoc213** [comment]
@budziq well, I can try another one :)... but I can't choose

**Comment by budziq** [comment]
@tyoc213 we are a little low on actionable and accepted examples ATM (I'll add some later on weekend). How about helping with https://github.com/brson/rust-cookbook/issues/182 ? I'll gladly guide you.
