### ISSUE TITLE
Encoding/decoding hex

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#115]

**Comment by vks** [comment]
As in #116, I would suggest to use [data-encoding](https://crates.io/crates/data-encoding).

**Comment by bjnyfv** [comment]
I wouldn't mind doing this one. As @vks suggested, I think that [data-encoding](https://crates.io/crates/data-encoding) would be a good choice.

If we go with the data-encoding crate, which version do we want to use? The crates.io page references version "1.2.0", but it appears that there is a release candidate version, "2.0.0-rc.1". The documentation link on crates.io seems to point to the documentation for version 2.

**Comment by bjnyfv** [comment]
Addressed in Pull Request #132.
