### ISSUE TITLE
Encoding/decoding base64

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#116]

**Comment by rap2hpoutre** [comment]
Ok I could try to write this example! Just one question before I actually write it: may I use [this crate](https://crates.io/crates/base64)?

**Comment by vks** [comment]
I prefer [data-encoding](https://crates.io/crates/data-encoding). It is more general and also faster (last time I tried).

**Comment by dtolnay** [comment]
If Hyper and Rustls are happy with `base64` then it's good enough for me.

**Comment by vks** [comment]
I don't find that argument very convincing. Anyway, it is not really important. I just think the duplication between `base64` and `hex` is unfortunate.

**Comment by dtolnay** [comment]
Added in #135.
