### ISSUE TITLE
Detect whether executable exists on system path

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#117]
Basically like Python's [`shutil.which`](https://docs.python.org/3/library/shutil.html#shutil.which).

**Comment by gsquire** [comment]
I can give this one a shot.

**Comment by dtolnay** [comment]
We decided to hold off on this because finding an executable is [way more complicated than I thought](https://github.com/fangyuanziti/which-rs/blob/master/src/lib.rs).
