### ISSUE TITLE
Get a Random Unused TCP/IP or UDP Port

### ISSUE THREAD

**Issue by xcthulhu** [brson/rust-cookbook#123]

**Comment by AndyGauge** [comment]
I'll give it a stab.  Do you think std::net::TcpListener would suffice or should this be Tokio?

**Comment by dtolnay** [comment]
I would stick with the standard library if possible. Though I have no idea how to implement this :sweat_smile: my first step would be rummaging through docs.

**Comment by fox0** [comment]
```rust
let socket = UdpSocket::bind("127.0.0.1:0").unwrap();
```

**Comment by xenowits** [comment]
```rust
use std::net::TcpListener;

let listener = TcpListener::bind("127.0.0.1:0").unwrap();
```
Binding with a port number of 0 will request that the OS assigns a port to this listener. The port allocated can be queried via the [TcpListener::local_addr](https://doc.rust-lang.org/std/net/struct.TcpListener.html#method.local_addr) method.

**Comment by SRYER** [comment]
Anyone knows if this will be fixed?

This works:

TcpListener::bind("127.0.0.1:0")

This does not:

UdpSocket::bind("127.0.0.1:0")

Use case:

Spinning up a new server in different integration tests will require such feature to be able to run in parallel without a big chunk of custom code to syncronize port scanning and allocation between the tests.
