### ISSUE TITLE
Recursively find all files with given predicate

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#125]
The predicate could be date, extension, size, executable flag, etc. For example recursively find all *.json files modified within the last 7 days.

The [`walkdir`](https://docs.rs/walkdir) crate will be useful.

**Comment by luisbg** [comment]
This sounds fun. Can I do this one while waiting for #110 ? :smile:

**Comment by dtolnay** [comment]
Of course, go for it!

**Comment by luisbg** [comment]
I'm at a Hackfest this weekend. So I will look at this then.

Thanks @dtolnay

**Comment by dtolnay** [comment]
Added in #146.
