### ISSUE TITLE
Recursively find duplicate file names

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#126]
Walk a directory and print out all file names that appear in more than one subdirectory. For example `a/b/cookbook.md` and `tmp/cookbook.md` would be considered duplicates and print "cookbook.md".

The [`walkdir`](https://docs.rs/walkdir) crate will be useful.

**Comment by xpayn** [comment]
i'd like to give it a try, but i have already submitted an example, and if someone wants to begin contributing with this issue, just ping me and i'll leave it to you.

**Comment by dtolnay** [comment]
Go for it, @xpayn! There are plenty of examples left.

**Comment by xpayn** [comment]
For this example there are multiple level of sophistication, and i don't know where to put the cursor.
- filter directories?
- ignore errors (permission denied for instance)?
- print a filename only once even if it's used more than twice?
- give the paths for each duplicated filename? 
- follow symlinks?

i guess it's a realism versus simplicity dilemma.
what's your opinion on that matter?

**Comment by dtolnay** [comment]
I would prefer to print the filename only once even if it's used more than twice, and not to print the paths for each duplicated filename. Other than that I would focus on being as realistic as possible without detracting from the intent of demonstrating how to recursively traverse a directory.
