### ISSUE TITLE
Styling of hyperlinked inline code items

### ISSUE THREAD

**Issue by budziq** [brson/rust-cookbook#142]
The default book.css renders inline code with hyperlink identically to standard inline code.
While most Markdown renderers would show them differently:
`Result`
[`Result`](https://doc.rust-lang.org/std/result/enum.Result.html)

This has a negative impact on our content ease of use / educational value (and actually makes it harder to make quality contribution as it is easy to omit needed links)

This is a duplicate from https://github.com/azerupi/mdBook/issues/261 but I have decided to copy it here as we will have to "rebase" our book.css to theirs once fix is available. Or we can just pull my hacky hotfix https://github.com/azerupi/mdBook/pull/289

**Comment by dtolnay** [comment]
I'd be happy to grab your css fix for now.
