### ISSUE TITLE
Capitalization in examples names

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#143]
Currently there is quite a mix:

> Download a file to a temporary directory *(sentence case)*

> Check if an API Resource Exists *(title case)*

> Listen on Unused port TCP/IP *(inconsistent)*

I have a preference for sentence case but whatever we agree on, it needs to be documented in CONTRIBUTING.md.

**Comment by budziq** [comment]
The title case seams to be standard for both [technical](http://shop.oreilly.com/category/series/cookbooks.do) and [literal](https://www.amazon.com/Jacques-P%C3%A9pin-New-Complete-Techniques-ebook/dp/B009XNXSJA/ref=zg_bs_6_1?_encoding=UTF8&psc=1&refRID=T4AC4Y1GGWNZ2F5YD200) "cookbooks" (at least for these few I have checked in past hour). 

On the other hand it will be slightly harder to contribute and require better proofreading.
I do not have strong preference here.

**Comment by dtolnay** [comment]
I look at it more as a list than as titles.

---

### Things you can do easily in Rust

- Read lines of strings from a file
- Generate random floating point numbers
- Maintain global mutable state
- Deserialize a TOML configuration file
- Run an External Command and Process Stdout

---

The title case one seems too shouty.

**Comment by budziq** [comment]
I can do this cleanup once https://github.com/brson/rust-cookbook/pull/155 is merged
