### ISSUE TITLE
Put a cache in front of the shields.io images

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#154]
Some shields.io requests are unreasonably slow. It should be okay to layer a 12-hour cache in front of them.

**Comment by jaemk** [comment]
I started throwing [something](https://github.com/jaemk/badge-cache) basic together. I can plop it on my server once I get to cleaning it up.

**Comment by dtolnay** [comment]
Wow! Thank you so much.

**Comment by dtolnay** [comment]
Fixed in #175.
