### ISSUE TITLE
"Expanded" examples in mdbook contain incorrect rustdoc boilerplate

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#161]
If you look at the examples on the [about](https://brson.github.io/rust-cookbook/about.html) page, you can click the 'expand' icon to _supposedly_ get the full source code, but it seems to be implicitly adding rustdoc-style boilerplate, which makes our examples completely bogus.

Presumably mdbook is mimicking rustdoc heuristics, looking for 'fn main', not finding it, and assuming it should be wrapping with its own main function.

Can this behavior be disabled @azerupi?

**Comment by dtolnay** [comment]
The code block on that page looks good to me. If you are hitting this after running `mdbook serve` locally, you need to install a newer version of mdBook.

**Comment by brson** [comment]
Oh, heh. The live version does look right. It's only locally that it looks wrong.
