### ISSUE TITLE
"find loops in filesystem"

### ISSUE THREAD

**Issue by budziq** [brson/rust-cookbook#207]
Use the [same-file](https://github.com/BurntSushi/same-file/) check if one of the files in given directory does not point to one of the path ancestors.

We would prefer not to use `walkdir` crate which already does al the heavy lifting here (using `same-file`) internally.

This might be a basis for a more involved example such as graphing the filesystem with petgraph but I would suggest to just implement the first trivial part of the example and we might think about creating a separate more involved one with petgraph.

cc https://github.com/brson/rust-cookbook/issues/205

**Comment by Ophirr33** [comment]
How would I go about creating a loop in the file system to test my program on? Trying to use a sym link just ends up creating a broken sym link for me.

**Comment by budziq** [comment]
@Ophirr33 try this
```bash
mkdir -p /tmp/foo/bar/baz
ln -s /tmp/foo/  /tmp/foo/bar/baz/qux
# and to test it ;)
ls /tmp/foo/bar/baz/qux/bar/baz/qux/bar/baz/qux
```
