### ISSUE TITLE
Logging to stdout instead of stderr

### ISSUE THREAD

**Issue by budziq** [brson/rust-cookbook#221]
Use [Builder::target](https://doc.rust-lang.org/log/env_logger/struct.Builder.html#method.target)

cc https://github.com/brson/rust-cookbook/issues/220

See [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by sb89** [comment]
Something like this?

```
#[macro_use]
extern crate log;
extern crate env_logger;

use env_logger::{LogBuilder, LogTarget};

fn main() {
    let mut builder = LogBuilder::new();
    builder.target(LogTarget::Stdout);
    builder.init().unwrap();

    error!("This error has been printied to Stdout");
}
```

**Comment by budziq** [comment]
yep :+1:  just add some prose and PR away :smile:

**Comment by sb89** [comment]
Great. What do you mean by "prose"?

**Comment by budziq** [comment]
A short textual description (in this case it would be a oneliner) ideally with hyperlinked reference to the key method.

**Comment by sb89** [comment]
OK, I understand. Thanks.
