### ISSUE TITLE
Use a custom environment variable to set up logging

### ISSUE THREAD

**Issue by budziq** [brson/rust-cookbook#222]
Use [Builder::parse](https://doc.rust-lang.org/log/env_logger/struct.Builder.html#method.parse)

cc https://github.com/brson/rust-cookbook/issues/220

See [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by yandexx** [comment]
I'll do this one.

**Comment by yandexx** [comment]
Well this was very confusing. All the docs everywhere mention `env_logger::Builder` but the actual struct is currently named `LogBuilder`.

https://doc.rust-lang.org/log/env_logger/struct.Builder.html

**Comment by budziq** [comment]
env_logger is currently under a rewrite most likely you have looked into docs from master instead of ones from published crate.

**Comment by yandexx** [comment]
I see. 

Is this example even needed if it's essentially the same as https://brson.github.io/rust-cookbook/logging.html#ex-log-timestamp but without `format()`?

**Comment by budziq** [comment]
yep but quite a lot of the description from that example should be moved to your example as this one would be more trivial and possitioned right above
