### ISSUE TITLE
add "read csv records with different delimeter"

### ISSUE THREAD

**Issue by budziq** [brson/rust-cookbook#229]
example should show reading csv with delimeter different than ','

cc https://github.com/brson/rust-cookbook/issues/212

See [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by somebrel** [comment]
I would like to work on this one

**Comment by alisha17** [comment]
@somebrel I was already working on this one. I mentioned in #212.

There are other ideas for more csv cookbook recipes. Did you have a look?

**Comment by somebrel** [comment]
Ops! Alright, I'll check them out, thanks
