### ISSUE TITLE
add "Extract a list of unique #Hashtags from a text" example

### ISSUE THREAD

**Issue by budziq** [brson/rust-cookbook#242]
This example should use [regex](https://crates.io/crates/regex) crate 
cc https://github.com/brson/rust-cookbook/issues/217

See [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by Phaiax** [comment]
I'm on this one.

**Comment by Phaiax** [comment]
Same question here: Which category should I use?

**Comment by budziq** [comment]
@phaiax sorry your question slipped past me. Regex examples generally go into basics section.
