### ISSUE TITLE
add "Extract all unique links from a MediaWiki markup" example

### ISSUE THREAD

**Issue by budziq** [brson/rust-cookbook#245]
This example should use [regex](https://crates.io/crates/regex) crate.

We may also like to provide an alternative implementation with [select](https://crates.io/crates/select) crate

cc https://github.com/brson/rust-cookbook/issues/217

See [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md) for details.

**Comment by yandexx** [comment]
I'll take this one.

Use `reqwest` to pull the page? Does this go into Networking or Basics?

**Comment by budziq** [comment]
There is no ideal answer as to which category given example might go into as these are cross cutting and we will have to redesign the presentation anyway to show that in the future(I would see the categories more like tags than chapters). 

If you plan to use reqwest then put it in networking.

Please note that we already have an [identical example using the select crate](https://brson.github.io/rust-cookbook/net.html#extract-all-links-from-a-webpage) which I've admittedly forgot about :/

I would suggest to propose a usecase which might be better suited for regex (or provide an expanded version that would use both select and regex) for instance:

- filtering or replacing the results from select with regex
- selecting some non html/json/xml remote content with regex
- your idea


@yandexx Would you be able to propose such a usecase? 
As a fallback we can provide a reimplementation of the https://brson.github.io/rust-cookbook/net.html#extract-all-links-from-a-webpage with regex (but I hope to avoid that)

**Comment by yandexx** [comment]
Thanks. A couple ideas came to mind:
- Find all links in a Mediawiki syntax page e.g. from https://en.wikipedia.org/w/index.php?title=Rust_(programming_language)&action=raw
- Find all links in a Markdown document e.g. https://raw.githubusercontent.com/BurntSushi/ripgrep/master/README.md (this sound more complex though since the actual URLs can be in the footer, so maybe find all headers or something).

**Comment by budziq** [comment]
Both ideas are very cool!

> this sounds more complex though since the actual URLs can be in the footer,

we would just extract links with capture groups for link name and link url in the form `[link name](scheme://some/path)` and disregard anything else no mater the location (we would just be interested in a list not their location so footer links would be good to)

I'll leave it up to you to chose the one that you find most useful, interesting and fun to implement :+1:

Just give me a heads-up of the one you choose to I can update the issue title.

**Comment by yandexx** [comment]
I figured Mediawiki is simpler so I'll implement it. I'll try to maybe look up both [[internal]] and [external] ones?

**Comment by budziq** [comment]
> I figured Mediawiki is simpler so I'll implement it. 

The syntax is actually more complex here but sure go wild :smile:

> I'll try to maybe look up both [[internal]] and [external] ones?
:+1:
