### ISSUE TITLE
The Run buttons use play.r-l.o, doesn't have any crates

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#32]
Some but not all of these examples would work if run with play.integer32.com instead.

![selection_041](https://cloud.githubusercontent.com/assets/1940490/25690790/cf97ce8a-3049-11e7-86fb-1c3cba8a152d.png)

**Comment by brson** [comment]
Yeah, not sure what do do. Maybe someday we can coordinate with play on a canonical crate list so that it mostly works.

**Comment by budziq** [comment]
Hi, I am really hyped for this initiative. 

Having cookbook spew compilation errors makes it less approachable and and reliable in the eyes of total newcommers (like myself).

I would suggest:
- disabling playpen for examples that are known not to work (if it is possible in mdbook)
- disabling playpen for all examples - for consistency sake
- using alternative playground (maybe with direct links) - https://play.integer32.com seams to have a good deal of crates preintalled and all of the (few) examples that I have checked work out of the box https://play.integer32.com/?gist=c0f035b47e1098793def1b8f23780e4c&version=undefined

**Comment by dtolnay** [comment]
For now I axed the Run buttons entirely in 323795ee8449e4d18096a18b2530b0b64988793c.

**Comment by dtolnay** [comment]
I opened https://github.com/brson/rust-cookbook/issues/87 to put back the "Run" button if we can make it work.
