### ISSUE TITLE
Add "Serialize a URL" example for url/serde crates

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#38]
Serializing urls with serde 1.0 is kinda weird, so maybe worth an example.

**Comment by budziq** [comment]
Hi,

I am not sure what is the exact idea for this example.
Until rust-url crate officially moves to serde-1.0 https://github.com/servo/rust-url/pull/327 the best that I've come up with is usage of auxiliary `url_serde` crate (but it would require adding it to Cargo.toml). Does it look ok? https://play.integer32.com/?gist=8199915f140db644a8bc3e480e582aea&version=undefined

If yes, I will make a PR.

cc @dtolnay

**Comment by dtolnay** [comment]
I would prefer to wait until we no longer need to use the roundabout approach. @SimonSapin

**Comment by budziq** [comment]
Will do. Thanks for your time :)

**Comment by budziq** [comment]
Judging from the original description I guess that the main reason for this example was the required roundabout approach. 
Once https://github.com/servo/rust-url/pull/327 is merged then the `Url` will serialize just like any other well behaved type and this example would be redundanta with https://brson.github.io/rust-cookbook/encoding.html.
So maybe just close this issue? @dtolnay

**Comment by dtolnay** [comment]
Yes I agree.
