### ISSUE TITLE
Make tables render a consistent width

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#42]
It's quite unattractive that the index tables all have different widths. There's surely some way to style them.

**Comment by rap2hpoutre** [comment]
According to http://azerupi.github.io/mdBook/format/theme/theme.html, the only way to customize table render seems so be creating a `theme/book.css` file, keep its original content, then add some CSS rules about tables. Is it overkill? Did I miss something?

**Comment by brson** [comment]
@rap2hpoutre That seems to be the case. If we have to copy their entire CSS maybe we can try to limit our custom CSS to one section of the file so it's easy to upgrade later. Are you interested in trying?

**Comment by rap2hpoutre** [comment]
Yes, I can try! I'm not a CSS expert but I think I can do something. Side note: there is an issue about custom CSS for mdBook: https://github.com/azerupi/mdBook/issues/178

**Comment by budziq** [comment]
I am no css expert either but adding `width: 100%` to `book.css` gives desired effect
```css
table {
  margin: 0 auto;
  border-collapse: collapse;
  width: 100%;
}
```
As this issue is already taken I will wait for something to open up ;)

**Comment by dtolnay** [comment]
I tried adding a src/theme/book.css but it didn't seem to get picked up by mdbook - http://localhost:3000/book.css was still serving the default one. @budziq I would love a PR if you get to it before @rap2hpoutre does.

**Comment by budziq** [comment]
@dtolnay done :)
As mentioned in the commit your problem was with https://github.com/azerupi/mdBook/issues/227. I had to implement the same workaround as the rust book
https://github.com/rust-lang/book/commit/371948a6b6ee71b2b7c55c4eb10e6faa6d511016

**Comment by dtolnay** [comment]
Reopening until we fix the column widths too. The tables are still misaligned because the three columns are different widths in each table.

**Comment by budziq** [comment]
I am completely out of my depth in regard to CSS but https://github.com/brson/rust-cookbook/pull/54 seams to give the expected result (I have tested on Linux Firefox and Chromium).

**Comment by rap2hpoutre** [comment]
@budziq Thanks!
