### ISSUE TITLE
Switch error handling setup to quick_main! macro from error-chain

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#59]
Right now the error handling pattern suggested by the cookbook's ['about'](https://brson.github.io/rust-cookbook/about.html#a-note-about-error-handling) page, and used in at least some of the examples, looks similar to `quick_main!`. Seems like we should just use that.

Switch the existing examples to replace 'main' with 'quick_main!', and update the about page.

cc @dtolnay @Yamakaky

**Comment by Yamakaky** [comment]
`quick_main!` was maid for that usecase ^^

**Comment by Yamakaky** [comment]
`quick_main!` was maid for that usecase ^^

I can do that

**Comment by budziq** [comment]
Using following form will hide part of doctest boilerplate from rendering but still allow for the code to compile and run under skeptic. 
<pre>
```
# fn main() {
#    run().unwrap();
# }
```
</pre>

It might make the existing snippets more ergonomic without the need to pull error-chain as dependency (or even hide error-chain noise if required)

cc @brson

**Comment by dtolnay** [comment]
Given that we don't have playground links (see #32), there needs to be a way to copy and run these examples. I would prefer not to hide main so that you can copy into a main.rs and expect it to work.

**Comment by brson** [comment]
Yes, I want to not hide code in the cookbook, have the examples say everything they are doing.
