### ISSUE TITLE
Broken Links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by sunjay** [brson/rust-cookbook#63]
According to [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md):
> This project is intended to be simple to contribute to, and to always have obvious next work items available.

That means it's probably important to let you know that the links and some of the formatting are broken in the contributing file. This is probably a really easy fix for someone looking to contribute. :smile: 

Issues I found while reading through [CONTRIBUTING.md](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md):
- [x] `[libz blitz]` does not link to anything (this link is used several times throughout the file)
- [x] `[crate-tasks]` does not link to anything
- [x] `["how to read this book"]` does not link to anything
- [x] The `Adding an example` link at the top of the file in the navigation links does not work
- [x] The `"a note about crate representation"` link in [Finding what to contribute](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md#finding-what-to-contribute) is broken and the section on the page it links to is empty
    - The section being empty is a bigger bug than the link being broken because it's not easy to know how to contribute if you were relying on that section to know which crates are being represented in the cookbook. I'm bringing this up because the file explicitly says:
        > If at any time there is not something obvious to contribute, that is a bug.
- [x] The `"A note about error handling"` link in [Example Guidelines](https://github.com/brson/rust-cookbook/blob/master/CONTRIBUTING.md#example-guidelines) is broken

**Comment by brson** [comment]
Haha yes, thank you. Most of these have obvious fixes. `[libz blitz]` goes to the irlo thread; `[crate-tasks]` to a GitHub query for that tag; "how to read this book" to the (empty) section in about.md; "a note about error handling" goes to the appropriate section in about.html.

Also, most of about.html is just [blank](https://github.com/brson/rust-cookbook/issues/new).

**Comment by brson** [comment]
Volunteers welcome to fix all this stuff. Since it's pretty important, if there's still more to do by Friday I'll pick some off myself.

**Comment by sunjay** [comment]
@brson I think you meant to link to the [issue you made about about.html](https://github.com/brson/rust-cookbook/issues/64), not the new issue page. :smile:

**Comment by brson** [comment]
Yep.

**Comment by rap2hpoutre** [comment]
> Volunteers welcome to fix all this stuff

I sent 4 PR, btw I'm not sure about the quality of my fixes. I hope it will help

**Comment by sunjay** [comment]
@rap2hpoutre Thanks for the PRs! I think it's fine this time, but for future reference I believe one PR would make this easier to review and merge. The fixes are pretty small and all related to the same issue, so it's okay for them to be grouped together. 

I went through and reviewed 3/4 of them so @brson can merge them when he next gets a chance. :smile:

**Comment by dtolnay** [comment]
Fixed in #66 and #73.
