### ISSUE TITLE
badges regarding log and syslog are incorrect

### ISSUE THREAD

**Issue by budziq** [brson/rust-cookbook#71]
Hi some of the crate badges have wrong version on them (the link is prepared for different crate for instance clap for log) 

Also in intro.md the category is "command line" instead of debugging for the log related examples.

Some of these problems are fixed in https://github.com/brson/rust-cookbook/pull/70
I will fix it later today once pulls are settled.

**Comment by dtolnay** [comment]
Thank you! Eventually we could even have a test that runs in Travis and makes sure all the badges are hooked up correctly.

**Comment by budziq** [comment]
I guess that it would have to be done anyway as currently there is no connection between version on the badge and one in the Cargo.toml which will be a problem at some point.
