### ISSUE TITLE
Badges are not synchronised with Cargo.toml

### ISSUE THREAD

**Issue by budziq** [brson/rust-cookbook#75]
Badges obtained from shields.io are always for the latest version available on crates.io
`https://img.shields.io/crates/v/clap.svg?label=clap`  ![clap](https://img.shields.io/crates/v/clap.svg?label=clap) currently shows 2.24.1 while in committed Cargo.lock clap has version 2.23.3.

This is somewhat low priority ATM but I am sure that it will become a problem once breaking changes of cookbook dependencies are published. Users will likely get build errors from posted examples misguided by the badge version incompatible with cookbook Cargo.lock.

Imho It would be best to:
- Have travis check versions - possibly with https://crates.io/crates/cargo-outdated (and eagerly update if there are no conflicts/failed tests?)
- Have badges reflect the actual version in Cargo.lock - currently i have no idea how to manage that

**Comment by dtolnay** [comment]
Yep this came up on IRC a couple days ago. Thanks for opening an issue!

My preference would be to remove Cargo.lock, set "*" dependencies in Cargo.toml, and hook up a daily Travis job to notify when an example fails to compile. This incentivizes us to keep the cookbook perfectly up to date and provides an easy opportunity for inexperienced contributors.

As needed, we can pin specific individual crates in Cargo.toml and their badge versions. I expect this to be rarely necessary.

**Comment by budziq** [comment]
Good idea, nice and simple :) Someone could make trivial changes:
- [ ] add build status badge to README.md
- [ ] update Cargo.toml dependency requirement to "*"
- [ ] remove Cargo.lock
- [ ] update deploy.sh to ignore `TRAVIS_EVENT_TYPE` == `cron`
- [ ] (optionaly) add build status badge to intro.md and/or about.md

But I guess one of the maintainers would need to configure the actual nightly build in travis

**Comment by dtolnay** [comment]
I set a daily Travis build.

**Comment by budziq** [comment]
Excellent! I don't want to kill all the easy contribution opportunities so I'll do it if no one steps up within a week.

**Comment by dtolnay** [comment]
I am satisfied with the solution in #118. I stuck a CI badge in the readme in 4a5c675e665c2ede7ff3a5f569f5d1af6d9ce55a.
