### ISSUE TITLE
POST the contents of a file to a REST api

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#90]
#80 added an example that shows posting a JSON body. Let's add a separate one to post the contents of a file.

**Comment by AndyGauge** [comment]
Sounds fun.  Making a slack webhook that allows the contents of a file to be url encoded and sent as a payload.  I've created a slack team for this purpose, rust-sample.

**Comment by AndyGauge** [comment]
The Slack API doesn't allow a file to be sent.  This turned out to only read the contents of a file and submit that to slack, which doesn't seem to be the intent of the issue.  Will rewrite for the Dropbox API.  Does the code for slack have a place in the cookbook?

**Comment by dtolnay** [comment]
How about https://paste.rs/ instead of Dropbox?

**Comment by AndyGauge** [comment]
You got it.  Auth is easier that way.
