### ISSUE TITLE
Iterate through paginated requests

### ISSUE THREAD

**Issue by dtolnay** [brson/rust-cookbook#92]
The crates.io API would be a good way to demonstrate this. A lot of their endpoints are limited to 100 elements per query, with a `page=2` parameter to see more elements.

```bash
curl -sS \
  -H 'Content-Type: application/json' \
  'https://crates.io/api/v1/crates/serde/reverse_dependencies?per_page=100&page=2'
```

**Comment by cetra3** [comment]
I could do this with an Iterator impl returning a `Dependency` struct, or is that a bit too complex?

**Comment by dtolnay** [comment]
I think that would work. Let's try it!
